name: OpenAPI
env:
  NODE_ENV: 'development'
  APPLICATION_MODE: 'api'

on:
  pull_request:
    branches:
      - master

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in openapi folder
        id: openapi-changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            openapi/**/*.ts
            src/balance-openapi/**/*.ts
    outputs:
      changed: ${{ steps.openapi-changes.outputs.any_changed }}

  check-flags:
    name: Check PR Title
    needs: [detect-changes, validate-title]
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.commit_message }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

  label-pr:
    name: Label PR
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: OpenAPI

  validate-title:
    name: Validate PR Title
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            refactor
            docs
          scopes: |
            openapi.types
            openapi
          requireScope: true

  canary-release:
    name: Canary Release
    needs: [detect-changes, check-flags, validate-title]
    if: ${{ contains(needs.check-flags.outputs.head-commit-message, '[canary]') && needs.detect-changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'development'
      APPLICATION_MODE: 'api'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: 'Authenticate with GitHub Packages'
        run: yarn auth
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Boostrap Yarn / Lerna
        run: |
          yarn --frozen-lockfile
          lerna bootstrap --ci

      - name: Build
        run: yarn lerna run build --since origin/master

      - name: Canary
        run: yarn lerna publish --force-publish --canary --preid dev --yes --dist-tag dev
