name: Release OpenAPI Stable Version

env:
  NODE_ENV: 'development'
  APPLICATION_MODE: 'api'

on: [workflow_dispatch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Config Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 'Authenticate with GitHub Packages'
        run: node npm-auth.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Yarn / Lerna
        run: |
          yarn --frozen-lockfile
          yarn add -W -D rdme 
          lerna bootstrap --ci

      - name: Build
        run: yarn lerna run build

      - name: Lerna Bump Packages Version - Stable Version
        run: |
          yarn lerna version --yes \
          --conventional-commits \
          --conventional-graduate \
          --create-release github \
          --tag-version-prefix='openapi@'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Lerna Version
        id: versions
        run: |
          echo "next=$(grep -m1 version lerna.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $GITHUB_OUTPUT
          echo "latest=$(yarn workspace @openapi/versions node cli.js)" >> $GITHUB_OUTPUT

      - name: Readme.io - Create Version
        run: |
          yarn rdme versions:create ${{ steps.versions.outputs.next }} \
          --main=false \
          --beta=false \
          --isPublic=false \
          --key=${{ secrets.READMEIO_API_KEY }} \
          --codename=v${{ steps.versions.outputs.next }} \
          --fork=${{ steps.versions.outputs.latest }}

      - name: Readme.io - Sync OpenAPI Spec
        run: |
          yarn rdme openapi ./openapi/packages/openapi/dist/openapi.json \
          --version=${{ steps.versions.outputs.new }} \
          --key=${{ secrets.READMEIO_API_KEY }} \
          --create
